---
# Ansible collection dependencies
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: community.vmware
    version: ">=4.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
