all:
  vars:
    ansible_user: ansible
    ansible_password: "{{ ansible_ssh_pass }}"
    ansible_python_interpreter: /usr/bin/python3.9
  children:
    # All RabbitMQ nodes (for provisioning/install)
    nodes:
      children:
        stretched_cluster:
        normal_cluster:

    # ============================================
    # Cluster 1: Stretched (Phoenix Metro Area)
    # Inter-site latency: ~2-5ms (metro WAN)
    # ============================================
    stretched_cluster:
      vars:
        rmq_cluster_name: phoenix
      children:
        phoenix_dc1:
        phoenix_dc2:

    phoenix_dc1:
      hosts:
        tanzu-node-01:
          ansible_host: 192.168.20.200
        tanzu-node-02:
          ansible_host: 192.168.20.201

    phoenix_dc2:
      hosts:
        tanzu-node-03:
          ansible_host: 192.168.20.202

    # ============================================
    # Cluster 2: Normal (Dallas)
    # All nodes in single DC, no added latency
    # ============================================
    normal_cluster:
      vars:
        rmq_cluster_name: dallas
      hosts:
        tanzu-node-04:
          ansible_host: 192.168.20.203
        tanzu-node-05:
          ansible_host: 192.168.20.204
        tanzu-node-06:
          ansible_host: 192.168.20.205

    vsphere:
      hosts:
        localhost:
          ansible_connection: local