all:
  vars:
    ansible_user: ansible
    ansible_password: "{{ ansible_ssh_pass }}"
    ansible_python_interpreter: /usr/bin/python3.9
  children:
    # All RabbitMQ nodes (for provisioning/install)
    nodes:
      children:
        arizona:
        texas:

    # ============================================
    # Region: Arizona (Primary)
    # Two DCs: Phoenix + Chandler (~3ms metro)
    # ============================================
    arizona:
      children:
        az_cluster_1:
        az_cluster_2:

    # AZ-Cluster-1: 1 node Phoenix, 2 nodes Chandler
    az_cluster_1:
      vars:
        rmq_cluster_name: az-cluster-1
        cluster_seed: az-rmq-01
      hosts:
        az-rmq-01:
          ansible_host: 192.168.20.200
          dc_group: phoenix_dc
        az-rmq-02:
          ansible_host: 192.168.20.201
          dc_group: chandler_dc
        az-rmq-03:
          ansible_host: 192.168.20.202
          dc_group: chandler_dc

    # AZ-Cluster-2: 2 nodes Phoenix, 1 node Chandler
    az_cluster_2:
      vars:
        rmq_cluster_name: az-cluster-2
        cluster_seed: az-rmq-04
      hosts:
        az-rmq-04:
          ansible_host: 192.168.20.203
          dc_group: phoenix_dc
        az-rmq-05:
          ansible_host: 192.168.20.204
          dc_group: phoenix_dc
        az-rmq-06:
          ansible_host: 192.168.20.205
          dc_group: chandler_dc

    # ============================================
    # Region: Texas (DR)
    # Two DCs: Dallas1 + Dallas2 (~3ms metro)
    # ============================================
    texas:
      children:
        tx_cluster_1:
        tx_cluster_2:

    # TX-Cluster-1: 1 node Dallas1, 2 nodes Dallas2
    tx_cluster_1:
      vars:
        rmq_cluster_name: tx-cluster-1
        cluster_seed: tx-rmq-01
      hosts:
        tx-rmq-01:
          ansible_host: 192.168.20.206
          dc_group: dallas1_dc
        tx-rmq-02:
          ansible_host: 192.168.20.207
          dc_group: dallas2_dc
        tx-rmq-03:
          ansible_host: 192.168.20.208
          dc_group: dallas2_dc

    # TX-Cluster-2: 2 nodes Dallas1, 1 node Dallas2
    tx_cluster_2:
      vars:
        rmq_cluster_name: tx-cluster-2
        cluster_seed: tx-rmq-04
      hosts:
        tx-rmq-04:
          ansible_host: 192.168.20.209
          dc_group: dallas1_dc
        tx-rmq-05:
          ansible_host: 192.168.20.210
          dc_group: dallas1_dc
        tx-rmq-06:
          ansible_host: 192.168.20.211
          dc_group: dallas2_dc

    # ============================================
    # Datacenter groups (for latency rules)
    # Hosts listed here without ansible_host since
    # it's already defined in the cluster groups above
    # ============================================
    phoenix_dc:
      hosts:
        az-rmq-01:
        az-rmq-04:
        az-rmq-05:

    chandler_dc:
      hosts:
        az-rmq-02:
        az-rmq-03:
        az-rmq-06:

    dallas1_dc:
      hosts:
        tx-rmq-01:
        tx-rmq-04:
        tx-rmq-05:

    dallas2_dc:
      hosts:
        tx-rmq-02:
        tx-rmq-03:
        tx-rmq-06:

    vsphere:
      hosts:
        localhost:
          ansible_python_interpreter: python
          ansible_connection: local
